#!/bin/bash
#set -x
read N_COUNT # Use a distinct variable name for clarity

SUM=0
# Initialize a loop counter
i=1
while [ $i -le $N_COUNT ]; do
 
    read N_INPUT 
    SUM=$(expr $N_INPUT + $SUM) 
    i=$(expr $i + 1)
done

if [ $N_COUNT -eq 0 ] || [ -z "$N_COUNT" ]; then
    echo "Error: Count cannot be zero or empty."
    exit 1
fi
AVERAGE=$(echo "scale=3; $SUM / $N_COUNT" | bc)
echo "$AVERAGE"
